version: '3.6'
services:
  web:
    shm_size: '256m'
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab
    hostname: 'linux-box1.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://linux-box1.local:8443'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8443:8443'
      - '2222:22'
    volumes:
      - '/mnt/media/_Gitlab/config:/etc/gitlab'
      - '/mnt/media/_Gitlab/logs:/var/log/gitlab'
      - '/mnt/media/_Gitlab/data:/var/opt/gitlab'
    restart: unless-stopped
