---
- name: "Update Machines"
  hosts: all
  become: yes
  tasks:
    - name: "Updating Debian/Ubuntu Machines"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
      #purge: yes

- name: "Update Containers"
  hosts: docker
  become: yes
  tasks:
    - name: "Running Watchtower Container"
      shell: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once"
      register: output
      changed_when: output.stderr_lines|length > 1
    #- debug: var=shell_output
