---
- name: "Update Machines"
  hosts: apt
  become: yes
  tasks:
  - name: "Updating machines that use apt"
    apt:
      update_cache: true
      upgrade: dist
      #cache_valid_time: 3600
      #force_apt_get: true

- name: "Update Docker Containers"
  hosts: docker
  become: yes
  gather_facts: no #docker is a subset of apt so don't need to do this twice
  tasks:
    - name: "Running watchtower container"
      shell: "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once"
      register: output
      changed_when: output.stderr_lines|length > 1
    #- debug: var=shell_output
